export interface BlockProps {
  flex: any,
  row: any,
  column: any,
  center: any,
  middle: any,
  left: any,
  right: any,
  top: any,
  bottom: any,
  card: any,
  shadow: any,
  color: any,
  space: any,
  padding: any,
  margin: any,
  animated: any,
  wrap: any,
  style: any,
};